// synnipaev/src/components/gallery/gallery_overlay.tsx
import React, { useEffect, useCallback } from 'react';

interface Photo {
    src: string;
    name: string;
}

interface GalleryOverlayProps {
    photos: Photo[];
    currentIndex: number;
    isOpen: boolean;
    onCloseOverlay: () => void;
    onUpdateIndex: (newIndex: number) => void;
}

const GalleryOverlay: React.FC<GalleryOverlayProps> = ({
    photos,
    currentIndex,
    isOpen,
    onCloseOverlay,
    onUpdateIndex,
}) => {
    const showNextImage = useCallback(() => {
        const nextIndex = (currentIndex + 1) % photos.length;
        onUpdateIndex(nextIndex);
    }, [currentIndex, photos.length, onUpdateIndex]);

    const showPreviousImage = useCallback(() => {
        const prevIndex = (currentIndex - 1 + photos.length) % photos.length;
        onUpdateIndex(prevIndex);
    }, [currentIndex, photos.length, onUpdateIndex]);

    const handleKeyDown = useCallback(
        (event: KeyboardEvent) => {
            switch (event.key) {
                case "Escape":
                    onCloseOverlay();
                    break;
                case "ArrowRight":
                    showNextImage();
                    break;
                case "ArrowLeft":
                    showPreviousImage();
                    break;
                default:
                    break;
            }
        },
        [onCloseOverlay, showNextImage, showPreviousImage]
    );

    useEffect(() => {
        if (isOpen) {
            window.addEventListener("keydown", handleKeyDown);
        }
        return () => {
            window.removeEventListener("keydown", handleKeyDown);
        };
    }, [isOpen, handleKeyDown]);

    if (!isOpen) return null;

    return (
        <div className="p-0 2xl:py-24 2xl:px-8 fixed inset-0 bg-dark/90 z-20 flex flex-row items-center justify-center">
            {/* Close Button */}
            <button onClick={onCloseOverlay} className="pt-8 pr-8 px-4 absolute top-0 right-0" aria-label="Close overlay">
                <svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M16.0585 13.2281L3.33038 0.5L0.501953 3.32843L13.23 16.0565L0.502255 28.7843L3.33068 31.6127L16.0585 18.8849L28.7862 31.6127L31.6147 28.7843L18.8869 16.0565L31.615 3.32846L28.7865 0.500031L16.0585 13.2281Z" fill="#EEEEEE" />
                </svg>
            </button>

            {/* Left Arrow */}
            <button
                onClick={showPreviousImage}
                className="m-4 z-30"
                aria-label="Previous image"
            >
                <svg width="19" height="32" viewBox="0 0 19 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M5.65699 15.9999L18.3848 3.27209L15.5563 0.443665L0 16L15.5567 31.5564L18.3851 28.728L5.65699 15.9999Z" fill="#EEEEEE" />
                </svg>
            </button>

            {/* Image and Description */}
            <div className="w-full items-center justify-center gap-8 flex-col flex">
                <img
                    className="w-full h-auto max-w-[100%] max-h-[80vh] object-contain"
                    src={photos[currentIndex].src}
                    alt={photos[currentIndex].name}
                />
                <h5 className="text-center text-white">{`${currentIndex + 1}/${photos.length}`}</h5>
            </div>

            {/* Right Arrow */}
            <button
                onClick={showNextImage}
                className="m-4 z-30"
                aria-label="Next image"
            >
                <svg width="19" height="32" viewBox="0 0 19 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M2.82843 0.443665L0 3.27209L12.7281 16.0002L0.000302076 28.728L2.82873 31.5564L18.3851 16L2.82843 0.443665Z" fill="#EEEEEE" />
                </svg>
            </button>
        </div>
    );
};

export default GalleryOverlay;

// ituk/src/components/cards/GalleryOverlay.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue';

interface Photo {
    src: string;
    name: string;
}

const props = defineProps({
    photos: {
        type: Array as () => Photo[],
        required: true,
    },
    currentIndex: {
        type: Number,
        required: true,
    },
    isOpen: {
        type: Boolean,
        required: true,
    },
});

const emit = defineEmits(['close-overlay', 'update-index']);

const handleClose = () => {
    emit('close-overlay');
};

const showNextImage = () => {
    if (props.currentIndex < props.photos.length - 1) {
        emit('update-index', props.currentIndex + 1);
    }
};

const showPreviousImage = () => {
    if (props.currentIndex > 0) {
        emit('update-index', props.currentIndex - 1);
    }
};

// Handle Keydown Events
const handleKeyDown = (event: KeyboardEvent) => {
    switch (event.key) {
        case 'Escape':
            handleClose();
            // console.log('Escape');
            break;
        case 'ArrowRight':
            showNextImage();
            // console.log('ArrowRight');
            break;
        case 'ArrowLeft':
            showPreviousImage();
            // console.log('ArrowLeft');
            break;
    }
};

onMounted(() => {
    window.addEventListener('keydown', handleKeyDown);
});

onUnmounted(() => {
    window.removeEventListener('keydown', handleKeyDown);
});
</script>


<template>
    <div v-if="isOpen"
        class="p-0 2xl:py-24 2xl:px-8 fixed inset-0 bg-dark/90 z-20 flex flex-row items-center justify-center">
        <!-- Close Button -->
        <button @click.prevent="handleClose" class="pt-8 pr-8 px-4 absolute top-0 right-0">
            <svg class="w-8 xl:w-16 h-8 xl:h-16" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
                <g fill="none" stroke="#EEEEEE" stroke-width="4">
                    <line x1="5" y1="5" x2="27" y2="27" />
                    <line x1="5" y1="27" x2="27" y2="5" />
                </g>
            </svg>
        </button>

        <!-- Left Arrow -->
        <button @click.prevent="showPreviousImage" :disabled="currentIndex === 0" class="m-4 z-30 disabled:opacity-0">
            <svg class="w-8 xl:w-16 h-8 xl:h-16" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M21 5L10 16L21 27" stroke="#EEEEEE" stroke-width="4" />
            </svg>
        </button>

        <!-- Image and Description -->
        <div class="w-full items-center justify-center gap-8 flex-col flex">
            <img class="w-full h-auto max-w-[100%] max-h-[80vh] object-contain" :src="photos[currentIndex].src"
                :alt="photos[currentIndex].name" />
            <h3 class="text-center">{{ photos[currentIndex].name }}</h3>
        </div>

        <!-- Right Arrow -->
        <button @click.prevent="showNextImage" :disabled="currentIndex === photos.length - 1"
            class="m-4 z-30 disabled:opacity-0">
            <svg class="w-8 xl:w-16 h-8 xl:h-16" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M10 27L21 16L10 5" stroke="#EEEEEE" stroke-width="4" />
            </svg>
        </button>
    </div>
</template>
