// synnipaev/src/app/[locale]/partnerlus/page.tsx
"use client"

import { db } from "@/firebase";
import { collection, getDocs, orderBy, query } from "firebase/firestore";
import { useEffect, useState } from "react";
import { DocumentData } from "firebase/firestore";
import Image from "next/image"
import netgroup from "@/assets/images/partners/netgroup.png"
import nortal from "@/assets/images/partners/nortal.png"
import { useDictionary } from "@/components/dictionary-provider";
import Card from "@/components/cards/card";
import { usePathname } from "next/navigation";

interface StudentOrg {
  name: string;
  en_name: string;
  imagePath: string;
  link: string;
  projects?: string[];
}

export default function Home() {
  const pathname = usePathname();
  const currentLocale = pathname?.split("/")[1];

  const dictionary = useDictionary().partners;

  const [studentOrgs, setStudentOrgs] = useState<StudentOrg[]>([]);

  const getStudentOrgs = async () => {
    try {
      const querySnapshot = await getDocs(
        query(collection(db, "partners"), orderBy("name", "asc"))
      );
      const orgs: StudentOrg[] = querySnapshot.docs.map((doc) => {
        const data = doc.data() as DocumentData;
        return {
          name: data.name,
          en_name: data.name_en,
          imagePath: data.imagePath,
          link: data.link,
          projects: data.projects,
        };
      });
      setStudentOrgs(orgs);
    } catch (error) {
      console.error("Error getting partners: ", error);
      throw error;
    }
  };
  useEffect(() => {
    getStudentOrgs();
  }, []);

  return (
    <div className="main-min">
      <div className="justify-center items-center bg-cooperation-bg bg-center bg-cover flex-row flex">
        <div className=" w-full h-full bg-extra justify-center items-center flex-row flex">
          <div className="main-padding w-full h-full bg-epic-gradient">
            <h1 className="text-center big">{dictionary.header}</h1>
          </div>
        </div>
      </div>

      <div className="main-padding items-center flex-col flex gap-16">
        <h2 className="text-center">{dictionary.partners}</h2>
        <div className="h-auto w-full justify-center items-center flex-col md:flex-row flex gap-16">
          <div className="self-stretch main-padding h-full md:w-1/2 bg-nortal rounded-2xl flex-col justify-center items-center flex">
            <Image src={nortal} alt="Nortal" />
          </div>
          <div className="self-stretch main-padding h-full md:w-1/2 bg-netgroup rounded-2xl flex-col justify-center items-center flex">
            <Image src={netgroup} alt="Netgroup" />
          </div>
        </div>
      </div>

      <div className="main-padding items-center flex-col flex gap-16">
        <h2 className="text-center break-all">{dictionary.studentorgs}</h2>
        <div className="grid min-w-full grid-cols-[repeat(auto-fit,minmax(17.75rem,1fr))] gap-8">
          {studentOrgs.map((partner, index) => (
            <Card key={index} link={partner.link} title={currentLocale === "en" ? partner.en_name : partner.name} image={partner.imagePath} listItems={partner.projects} type="list" />
          ))}
        </div>
      </div>

      <div className="main-padding bg-primary justify-center items-center gap-16 flex-col xl:flex-row flex">
        <h2 className="text-center w-full">{dictionary.offer}</h2>
        <div className=" justify-between items-center flex-col md:flex-row flex gap-16">
          <p className="items-center flex-col flex gap-4 transform transition-transform duration-300 hover:scale-125 hover:select-none">
            <span className="big font-bold">{dictionary.statistics.stat1.title}</span>
            {dictionary.statistics.stat1.description}
          </p>
          <p className="items-center flex-col flex gap-4 transform transition-transform duration-300 hover:scale-125 hover:select-none">
            <span className="big font-bold">{dictionary.statistics.stat2.title}</span>
            {dictionary.statistics.stat2.description}
          </p>
          <p className="items-center flex-col flex gap-4 transform transition-transform duration-300 hover:scale-125 hover:select-none">
            <span className="big font-bold">{dictionary.statistics.stat3.title}</span>
            {dictionary.statistics.stat3.description}
          </p>
          <p className="items-center flex-col flex gap-4 transform transition-transform duration-300 hover:scale-125 hover:select-none">
            <span className="big font-bold">{dictionary.statistics.stat4.title}</span>
            {dictionary.statistics.stat4.description}
          </p>
        </div>
      </div>

      <div className="main-padding justify-center items-center gap-16 flex-col flex">
        <h2 className="text-center">{dictionary.wish}</h2>
        <p className="text-center">{dictionary.goal}</p>
        <h3 className="text-center">{dictionary.contact} <a className="contact text-secondary underline" href="mailto:kontakt@ituk.ee">kontakt@ituk.ee</a> {dictionary.contact2}</h3>
      </div>
    </div>
  )
}

// ituk.ee/src/routes/partnerlus/+page.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import * as m from "$lib/paraglide/messages";
    import { getLocale } from "$lib/paraglide/runtime";
    import PageHeader from "$lib/components/PageHeader.svelte";
    import Statistics from "$lib/components/Statistics.svelte";
    import Card from "$lib/components/Card.svelte";
    import { getPartners, type Partner } from "$lib/firebase";
    import SEO from "$lib/components/SEO.svelte";
    import { SOCIAL_STATS, EVENTS_PER_YEAR } from "$lib/config/stats";

    let studentOrgs = $state<Partner[]>([]);
    let loading = $state(true);
    let error = $state<string | null>(null);

    onMount(async () => {
        try {
            studentOrgs = await getPartners();
        } catch (e) {
            console.error("Error loading student orgs:", e);
            error = "Failed to load student organizations";
        } finally {
            loading = false;
        }
    });

    function getLocalizedName(org: Partner): string {
        return getLocale() === "en" && org.name_en ? org.name_en : org.name;
    }
</script>

<SEO pageKey="partnerlus" />

<div>
    <PageHeader
        title={m.partners_header()}
        backgroundImage="/headers/cooperation.jpg"
    />

    <!-- Partners Section -->
    <div
        class="section-padding container-content items-center flex-col flex gap-8"
    >
        <h2 class="text-center">{m.partners_partners()}</h2>
        <div class="w-full flex flex-col sm:flex-row items-stretch gap-8">
            <a
                target="_blank"
                href="https://nortal.com/"
                class="flex-1 h-24 sm:h-32 p-4 bg-nortal rounded-xl flex justify-center items-center overflow-hidden"
            >
                <img
                    src="/images/partners/nortal.png"
                    alt="Nortal"
                    class="object-contain w-full h-full"
                    loading="lazy"
                />
            </a>
            <a
                target="_blank"
                href="https://netgroup.com/"
                class="flex-1 h-24 sm:h-32 p-4 bg-netgroup rounded-xl flex justify-center items-center overflow-hidden"
            >
                <img
                    src="/images/partners/netgroup.png"
                    alt="Netgroup"
                    class="object-contain w-full h-full"
                    loading="lazy"
                />
            </a>
            <a
                target="_blank"
                href="https://www.alecoq.ee/"
                class="flex-1 h-24 sm:h-32 p-4 bg-alecoq rounded-xl flex justify-center items-center overflow-hidden"
            >
                <img
                    src="/images/partners/alecoq.png"
                    alt="A.LeCoq"
                    class="object-contain w-full h-full"
                    loading="lazy"
                />
            </a>
            <a
                target="_blank"
                href="https://dominospizza.ee/"
                class="flex-1 h-24 sm:h-32 p-4 bg-dominos rounded-xl flex justify-center items-center overflow-hidden"
            >
                <img
                    src="/images/partners/dominos.png"
                    alt="Domino's"
                    class="object-contain w-full h-full"
                    loading="lazy"
                />
            </a>
        </div>
    </div>

    <!-- Student Orgs Section -->
    <div
        class="section-padding container-content items-center flex-col flex gap-8"
    >
        <h2 class="text-center">{m.partners_studentorgs()}</h2>
        {#if loading}
            <p class="text-gray">{m.common_loading()}</p>
        {:else if error}
            <p class="text-red-500">{error}</p>
        {:else if studentOrgs.length === 0}
            <p class="text-gray">No student organizations found</p>
        {:else}
            <div
                class="grid min-w-full grid-cols-1 gap-8 xs:grid-cols-2 lg:grid-cols-4 justify-items-center"
            >
                {#each studentOrgs as org}
                    <Card
                        link={org.link}
                        title={getLocalizedName(org)}
                        image={org.imagePath}
                        listItems={org.projects}
                        type="list"
                    />
                {/each}
            </div>
        {/if}
    </div>

    <!-- Statistics Section -->
    <Statistics
        title={m.partners_offer()}
        items={[
            {
                value: SOCIAL_STATS.instagram.followers,
                label: m.partners_stat1_description(),
                link: SOCIAL_STATS.instagram.link,
            },
            {
                value: SOCIAL_STATS.facebook.followers,
                label: m.partners_stat2_description(),
                link: SOCIAL_STATS.facebook.link,
            },
            {
                value: SOCIAL_STATS.discord.members,
                label: m.partners_stat3_description(),
                link: SOCIAL_STATS.discord.link,
            },
            {
                value: EVENTS_PER_YEAR,
                label: m.partners_stat4_description(),
                link: "/uritused",
            },
        ]}
    />

    <!-- CTA Section -->
    <div
        class="section-padding container-content justify-center items-center gap-16 flex-col md:flex-row flex"
    >
        <div class="w-full md:w-1/2 flex flex-col gap-8">
            <h2>{m.partners_wish()}</h2>
            <p>{m.partners_goal()}</p>
            <h3>
                {m.partners_contact()}
                <a
                    class="text-primary underline hover:brightness-125"
                    href="mailto:kontakt@ituk.ee">kontakt@ituk.ee</a
                >
                {m.partners_contact2()}
            </h3>
        </div>
        <div class="w-full md:w-1/2">
            <img
                src="/images/koostoo.jpg"
                alt=""
                class="rounded-xl object-cover w-full h-72"
            />
        </div>
    </div>
</div>
