// ituk.ee/src/routes/meist/+page.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import { getLocale } from "$lib/paraglide/runtime";
    import * as m from "$lib/paraglide/messages";
    import {
        getBoardMembers,
        getTimelineEvents,
        getSetting,
        type BoardMember,
        type TimelineEvent,
    } from "$lib/firebase";
    import PageHeader from "$lib/components/PageHeader.svelte";
    import Card from "$lib/components/Card.svelte";
    import Statistics from "$lib/components/Statistics.svelte";
    import TimelineDesktop from "$lib/components/TimelineDesktop.svelte";
    import SEO from "$lib/components/SEO.svelte";

    let boardMembers = $state<BoardMember[]>([]);
    let timelineEvents = $state<TimelineEvent[]>([]);
    let boardYear = $state("2024/2025");
    let loading = $state(true);
    let error = $state<string | null>(null);

    onMount(async () => {
        try {
            const [members, events, year] = await Promise.all([
                getBoardMembers(),
                getTimelineEvents(),
                getSetting("boardYear"),
            ]);
            boardMembers = members;
            timelineEvents = events;
            if (year) boardYear = year;
        } catch (e) {
            console.error("Error loading data:", e);
            error = "Failed to load data";
        } finally {
            loading = false;
        }
    });

    const isEnglish = $derived(getLocale() === "en");
</script>

<SEO pageKey="meist" />

<div>
    <PageHeader
        title={m.aboutus_whatis()}
        backgroundImage="/headers/meist.jpg"
    />

    <!-- What is ITÜK Section -->
    <div
        class="section-padding container-content flex flex-col lg:flex-row gap-16 items-center"
    >
        <div class="flex flex-col gap-8">
            <h2>{m.aboutus_answer()}</h2>
            <p>{m.aboutus_answer2()}</p>
            <p>{m.aboutus_answer3()}</p>
        </div>
        <div
            class="h-full justify-center items-stretch flex-col xs:flex-row flex gap-8"
        >
            <Card
                image="/images/uritused.jpg"
                title={m.aboutus_card1_title()}
                description={m.aboutus_card1_description()}
                type="default"
            />
            <Card
                image="/images/sobrad.jpg"
                title={m.aboutus_card2_title()}
                description={m.aboutus_card2_description()}
                type="default"
            />
        </div>
    </div>

    <!-- Statistics Section -->
    <Statistics
        title={m.aboutus_numbers()}
        items={[
            {
                value: m.aboutus_stat1_title(),
                label: m.aboutus_stat1_description(),
            },
            {
                value: m.aboutus_stat2_title(),
                label: m.aboutus_stat2_description(),
            },
            {
                value: m.aboutus_stat3_title(),
                label: m.aboutus_stat3_description(),
            },
            {
                value: m.aboutus_stat4_title(),
                label: m.aboutus_stat4_description(),
            },
        ]}
    />

    <!-- Structure Section -->
    <div
        class="section-padding container-content flex flex-col md:flex-row gap-16 items-center"
    >
        <div class="w-full md:w-1/2 flex flex-col gap-8">
            <h2>{m.aboutus_structure()}</h2>
            <p>{m.aboutus_howmany()}</p>
            <ul>
                <li>{m.aboutus_status1()}</li>
                <li>{m.aboutus_status2()}</li>
                <li>{m.aboutus_status3()}</li>
                <li>{m.aboutus_status4()}</li>
            </ul>
            <p>{m.aboutus_structure2()}</p>
            <p>{m.aboutus_structure3()}</p>
        </div>
        <div class="w-full md:w-1/2 flex flex-col items-center gap-8">
            <img
                class="w-full"
                src="/images/ituk_struktuur_2026.png"
                alt="ITÜKi struktuur 2026"
            />
            <p class="text-gray">{m.aboutus_structure4()}</p>
        </div>
    </div>

    <!-- Board Section -->
    <div
        class="section-padding container-content flex flex-col gap-8 items-center"
    >
        <h2 class="text-center">{m.aboutus_boardtitle({ year: boardYear })}</h2>
        {#if loading}
            <p class="text-gray">{m.common_loading()}</p>
        {:else if error}
            <p class="text-red-500">{error}</p>
        {:else}
            <div
                class="grid w-full grid-cols-1 gap-4 sm:gap-8 xs:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 justify-items-center"
            >
                {#each boardMembers as member}
                    <Card
                        title={member.name}
                        image={member.imagePath}
                        description={isEnglish
                            ? member.position_en
                            : member.position}
                        type="board"
                        email={member.email}
                    />
                {/each}
            </div>
        {/if}
    </div>

    <!-- History Section (Desktop only) -->
    <div
        class="section-padding container-content hidden lg:flex flex-col gap-8 items-center"
    >
        <h2 class="text-center">{m.aboutus_historytitle()}</h2>
        {#if loading}
            <p class="text-gray">{m.common_loading()}</p>
        {:else if error}
            <p class="text-red-500">{error}</p>
        {:else}
            <TimelineDesktop items={timelineEvents} />
        {/if}
        <h3 class="text-center">
            ...ja kui tuleb veel huvitavaid asju, siis lisame siia!
        </h3>
    </div>
</div>

// src/app/[locale]/meist/page.tsx
"use client";

import { db } from "@/firebase";
import { collection, getDocs, orderBy, query } from "firebase/firestore";
import { useEffect, useState } from "react";
import { DocumentData } from "firebase/firestore";
import Card from "@/components/cards/card";
import Timeline from "@/components/timeline";
import PageHeader from "@/components/page-header";
import Statistics from "@/components/statistics";
import uritused from "@/assets/images/uritused.jpg";
import sobrad from "@/assets/images/sobrad.jpg";
import { useDictionary } from "@/components/dictionary-provider";
import { usePathname } from "next/navigation";
import ituk_struktuur from "@/assets/images/ituk_struktuur.png";
import Image from "next/image";

interface BoardMember {
  name: string;
  position: string;
  en_position: string;
  email: string;
  imagePath: string;
}

interface Event {
  title: string;
  description: string;
  imagePath: string;
  year: Date;
}

export default function Home() {
  //get dictionary
  const pathname = usePathname();
  const currentLocale = pathname?.split("/")[1];

  const dictionary = useDictionary().aboutus;

  const [boardMembers, setBoardMembers] = useState<BoardMember[]>([]);
  const [events, setEvents] = useState<Event[]>([]);

  const getBoardMembers = async () => {
    try {
      const querySnapshot = await getDocs(
        query(collection(db, "board"), orderBy("imagePath", "asc"))
      );
      const members: BoardMember[] = querySnapshot.docs.map((doc) => {
        const data = doc.data() as DocumentData;
        return {
          name: data.name,
          position: data.position,
          en_position: data.position_en,
          email: data.email,
          imagePath: data.imagePath,
        };
      });
      setBoardMembers(members);
    } catch (error) {
      console.error("Error getting members: ", error);
      throw error;
    }
  };

  const getEvents = async () => {
    try {
      const q = query(collection(db, "timeline-events"), orderBy("year"));
      const querySnapshot = await getDocs(q);
      const events: Event[] = querySnapshot.docs.map((doc) => {
        const data = doc.data() as DocumentData;
        return {
          title: data.title,
          description: data.description,
          imagePath: data.imagePath,
          year: data.year.toDate(),
        };
      });
      setEvents(events);
    } catch (error) {
      console.error("Error getting events: ", error);
      throw error;
    }
  };

  useEffect(() => {
    getBoardMembers();
    getEvents();
  }, []);

  return (
    <div>
      <PageHeader title={dictionary.whatis} backgroundImage="/headers/about.jpg" />

      <div className="section-padding container-content justify-center items-center text-align gap-16 flex-col lg:flex-row flex">
        <div className="flex-col flex gap-8">
          <h2>{dictionary.answer}</h2>
          <p>
            {dictionary.answer2}
            <br /><br />
            {dictionary.answer3}
          </p>
        </div>
        <div className="h-full justify-center items-stretch flex-col sm:flex-row flex gap-8">
          <Card image={uritused.src} title={dictionary.card1.title} description={dictionary.card1.description} type="default" />
          <Card image={sobrad.src} title={dictionary.card2.title} description={dictionary.card2.description} type="default" />
        </div>
      </div>

      <Statistics
        title={dictionary.numbers} items={[
          { value: dictionary.statistics.stat1.title, label: dictionary.statistics.stat1.description },
          { value: dictionary.statistics.stat2.title, label: dictionary.statistics.stat2.description },
          { value: dictionary.statistics.stat3.title, label: dictionary.statistics.stat3.description },
          { value: dictionary.statistics.stat4.title, label: dictionary.statistics.stat4.description },
        ]} />

      <div className="section-padding container-content justify-center items-center gap-16 flex-col md:flex-row flex">
        <div className="w-full md:w-1/2 flex-col flex gap-8">
          <h2>
            {dictionary.structure}
          </h2>
          <p>
            {dictionary.howmany}
          </p>
          <ul>
            <li>{dictionary.statuses.status1}</li>
            <li>{dictionary.statuses.status2}</li>
            <li>{dictionary.statuses.status3}</li>
            <li>{dictionary.statuses.status4}</li>
          </ul>
          <p>
            {dictionary.structure2}
            <br /><br />
            {dictionary.structure3}
          </p>
        </div>
        <Image className="w-full md:w-1/2" src={ituk_struktuur} alt="ITÜKi struktuur 2025" />
      </div>

      <div className="section-padding container-content justify-center items-center text-align gap-16 flex-col flex">
        <h2>{dictionary.boardtitle}</h2>
        <div className="grid min-w-full grid-cols-1 gap-8 xs:grid-cols-2 lg:grid-cols-4">
          {boardMembers.map((member, index) => (
            <Card key={index} title={member.name} image={member.imagePath} description={currentLocale === "en" ? member.en_position : member.position} type="board" email={member.email} />
          ))}
        </div>
        <h2>{dictionary.historytitle}</h2>
        <div className="flex flex-col justify-center items-center">
          <Timeline type="start" />
          {events.map((event, index) => (
            <Timeline key={index} type={index % 2 === 0 ? "left" : "right"} imagePath={event.imagePath} title={event.title} description={event.description} year={event.year} />
          ))}
          <Timeline type="end" />
        </div>
        <h3>...ja kui tuleb veel huvitavaid asju, siis lisame siia!</h3>
      </div>
    </div >
  );
}
