// src/app/[locale]/uritused/[type]/[event]/[year]/page.tsx
"use client"

import Loading from "@/components/animations/loading";
import { useDictionary } from "@/components/dictionary-provider";
import { db } from "@/firebase";
import { collection, doc, DocumentData, getDocs, query, where } from "firebase/firestore";
import { usePathname } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import Gallery from "@/components/gallery/gallery";

interface EventYear {
    key: string;
    banner: string;
    date: string;
    description: string;
    en_description: string;
    extraInformation?: string;
    en_extraInformation?: string;
    handle: string;
    gallery?: Map<string, string>;
    title: string;
    en_title: string;
}

export default function Year({
    params: paramsPromise,
}: {
    params: Promise<{ event: string, year: string }>;
}) {
    const pathname = usePathname();
    const currentLocale = pathname?.split("/")[1];

    const dictionary = useDictionary().year;

    const [eventHandle, setEventHandle] = useState<string>("");
    const [year, setYear] = useState<string>("");
    const [eventYear, setEventYear] = useState<EventYear>();

    useEffect(() => {
        async function unwrapParams() {
            const params = await paramsPromise;
            setEventHandle(params.event);
            setYear(params.year);
        }
        unwrapParams();
    }, [paramsPromise]);

    const getYear = useCallback(async () => {
        if (!eventHandle) return;

        try {
            const eventQuerry = query(
                collection(db, "events"),
                where("handle", "==", eventHandle)
            );
            const eventQuerySnapshot = await getDocs(eventQuerry);
            const eventRef = doc(db, "events", eventQuerySnapshot.docs[0].id);
            const yearRef = collection(eventRef, "years");
            const q = query(yearRef, where("handle", "==", year))
            const yearQuerySnapshot = await getDocs(q);

            const data = yearQuerySnapshot.docs[0].data() as DocumentData;
            const eventYear: EventYear = {
                key: yearQuerySnapshot.docs[0].id,
                banner: data.banner,
                date: data.date,
                description: data.description,
                en_description: data.description_en,
                extraInformation: data.extraInformation ? data.extraInformation : undefined,
                en_extraInformation: data.extraInformation_ ? data.extraInformation_ : undefined,
                gallery: data.gallery ? new Map(Object.entries(data.gallery)) : undefined,
                handle: data.handle,
                title: data.title,
                en_title: data.title_en
            };
            console.log(eventYear);
            setEventYear(eventYear);
        } catch (error) {
            console.error("Error getting members: ", error);
            throw error;
        }
    }, [eventHandle])

    useEffect(() => {
        getYear();
    }, [getYear]);

    if (eventYear) {
        return (
            <div>
                <div className="flex flex-col items-center">
                    <div
                        className="items-center justify-center h-full w-full bg-center bg-cover flex-row flex"
                        style={{ backgroundImage: `url(${eventYear.banner})` }}
                    >
                        <div className="section-padding w-full bg-black/50 justify-center items-center flex-row flex">
                            <h1 className="text-big text-center">{currentLocale === "en" ? eventYear.en_title : eventYear.title}</h1>
                        </div>
                    </div>

                    <div className="section-padding container-content justify-center items-start flex-col flex gap-16">
                        <div className="w-full justify-center items-start flex-col md:flex-row flex gap-16">
                            <div className="w-full justify-center items-start flex-col flex gap-16">
                                <h2>{dictionary.description}</h2>
                                <div>
                                    {(currentLocale === "en" ? eventYear.en_description : eventYear.description)
                                        ?.split("\n")
                                        .map((line, index) => (
                                            <p key={index}>
                                                {line}
                                                <br />
                                                <br />
                                            </p>
                                        ))}
                                </div>
                            </div>

                            {eventYear.extraInformation && eventYear.extraInformation.length > 0 && (
                                <div className="w-full justify-center items-start flex-col flex gap-16">
                                    <h3>{dictionary.extrainformation}</h3>
                                    <div>
                                        {(currentLocale === "en" ? eventYear.en_extraInformation : eventYear.extraInformation)
                                            ?.split("\n")
                                            .map((line, index) => (
                                                <p key={index}>
                                                    {line}
                                                    <br />
                                                    <br />
                                                </p>
                                            ))}
                                    </div>
                                </div>
                            )}
                        </div>
                    </div>

                    {eventYear.gallery && eventYear.gallery.size > 0 && (
                        <div className="section-padding container-content justify-center items-start flex-col flex gap-8">
                            <h3>{dictionary.gallery}</h3>
                            <Gallery
                                photos={Array.from(eventYear.gallery.entries()).map(([name, src]) => ({
                                    src,
                                    name,
                                }))}
                            />
                        </div>
                    )}
                </div>
            </div>
        )
    } else {
        return (
            <div className="justify-center items-center flex-col flex gap-8">
                <h2>Laeb...</h2>
                <Loading />
            </div>
        );
    }
}

// ituk.ee/src/routes/uritused/[type]/[event]/[year]/+page.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import { page } from "$app/stores";
    import * as m from "$lib/paraglide/messages";
    import { getLocale } from "$lib/paraglide/runtime";
    import { getEventYear, type EventYear } from "$lib/firebase";
    import SEO from "$lib/components/SEO.svelte";
    import Loading from "$lib/components/Loading.svelte";
    import Gallery from "$lib/components/Gallery.svelte";

    let eventYear = $state<EventYear | null>(null);
    let loading = $state(true);
    let eventHandle = $derived($page.params.event ?? "");
    let yearHandle = $derived($page.params.year ?? "");
    let isEnglish = $derived(getLocale() === "en");

    onMount(async () => {
        try {
            if (eventHandle && yearHandle)
                eventYear = await getEventYear(eventHandle, yearHandle);
        } catch (error) {
            console.error("Error loading event year:", error);
        } finally {
            loading = false;
        }
    });
</script>

<SEO pageKey="uritused" />

{#if loading}
    <div class="flex flex-col items-center justify-center gap-8 min-h-[50vh]">
        <h2>Laeb...</h2>
        <Loading />
    </div>
{:else if eventYear}
    <div class="flex flex-col items-center">
        <div
            class="items-center justify-center h-full w-full bg-center bg-cover flex-row flex"
            style="background-image: url({eventYear.banner})"
        >
            <div
                class="section-padding w-full bg-black/50 justify-center items-center flex-row flex"
            >
                <h1 class="text-big text-center">
                    {isEnglish ? eventYear.title_en : eventYear.title}
                </h1>
            </div>
        </div>

        <div
            class="section-padding container-content justify-center items-start flex-col flex gap-16"
        >
            <div
                class="w-full justify-center items-start flex-col md:flex-row flex gap-16"
            >
                <div
                    class="w-full justify-center items-start flex-col flex gap-16"
                >
                    <h2>{m.year_description()}</h2>
                    <div>
                        {#each (isEnglish ? eventYear.description_en : eventYear.description)?.split("\n") ?? [] as line}
                            <p>
                                {line}
                                <br /><br />
                            </p>
                        {/each}
                    </div>
                </div>

                {#if eventYear.extraInformation && eventYear.extraInformation.length > 0}
                    <div
                        class="w-full justify-center items-start flex-col flex gap-16"
                    >
                        <h3>{m.year_extrainformation()}</h3>
                        <div>
                            {#each (isEnglish ? eventYear.extraInformation_en : eventYear.extraInformation)?.split("\n") ?? [] as line}
                                <p>
                                    {line}
                                    <br /><br />
                                </p>
                            {/each}
                        </div>
                    </div>
                {/if}
            </div>
        </div>

        {#if eventYear.gallery && Object.keys(eventYear.gallery).length > 0}
            <div
                class="section-padding container-content justify-center items-start flex-col flex gap-8"
            >
                <h3>{m.year_gallery()}</h3>
                <Gallery
                    photos={Object.entries(eventYear.gallery).map(
                        ([name, src]) => ({
                            src,
                            name,
                        }),
                    )}
                />
            </div>
        {/if}
    </div>
{:else}
    <div class="flex flex-col items-center justify-center gap-8 min-h-[50vh]">
        <p class="text-gray">Event year not found</p>
    </div>
{/if}
