// synnipaev/src/app/[locale]/liitu/page.tsx
"use client"

import Card from "@/components/cards/card";
import { useDictionary } from "@/components/dictionary-provider"
import uritused from "@/assets/images/uritused.jpg"

export default function Home() {
    const dictionary = useDictionary().join;
    return(
        <div>
            <div className="justify-center items-center bg-join-bg bg-center bg-cover flex-row flex">
                <div className=" w-full h-full bg-extra justify-center items-center flex-row flex">
                <div className="main-padding w-full h-full bg-epic-gradient">
                    <h1 className="text-center big">{dictionary.header}</h1>
                </div>
                </div>
            </div>

            <div className="flex flex-col justify-center items-center px-16 py-32 gap-16">
                <h1>{}</h1>
                <div className="flex flex-row items-center gap-16">
                    <Card title={dictionary.card1.title} image={uritused.src} description={dictionary.card1.description} board={false} />
                    <Card title={dictionary.card2.title} image={uritused.src} description={dictionary.card2.description} board={false} />
                    <Card title={dictionary.card3.title} image={uritused.src} description={dictionary.card3.description} board={false} />
                    <Card title={dictionary.card4.title} image={uritused.src} description={dictionary.card4.description} board={false} />
                </div>
            </div>
        </div>
    )
}

// ituk.ee/src/routes/liitu/+page.svelte
<script lang="ts">
    import * as m from "$lib/paraglide/messages";
    import PageHeader from "$lib/components/PageHeader.svelte";
    import Card from "$lib/components/Card.svelte";
</script>

<div>
    <PageHeader title={m.join_header()} backgroundImage="/headers/liitu.jpg" />

    <div
        class="section-padding container-content flex flex-col justify-center items-center gap-8"
    >
        <h2>{m.join_text1()}</h2>
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">
            <Card
                title={m.join_card1_title()}
                image="/images/uritused.jpg"
                description={m.join_card1_description()}
                type="default"
            />
            <Card
                title={m.join_card2_title()}
                image="/images/uritused.jpg"
                description={m.join_card2_description()}
                type="default"
            />
            <Card
                title={m.join_card3_title()}
                image="/images/uritused.jpg"
                description={m.join_card3_description()}
                type="default"
            />
            <Card
                title={m.join_card4_title()}
                image="/images/uritused.jpg"
                description={m.join_card4_description()}
                type="default"
            />
        </div>
        <p class="text-center">{m.join_text2()}</p>
    </div>
</div>
