// ituk/src/components/buttons/HamburgerMenu.vue
<template>
    <button aria-label="Hamburger Menu" class="w-8 h-8 flex flex-col justify-between items-center relative">
        <div :class="[
            'w-8 h-1 bg-white transition-all duration-300 ease-in-out',
            isOpen ? 'rotate-45 translate-y-[15.8px] w-[40px]' : ''
        ]"></div>
        <div :class="[
            'w-8 h-1 bg-white transition-all duration-300 ease-in-out',
            isOpen ? 'opacity-0' : ''
        ]"></div>
        <div :class="[
            'w-8 h-1 bg-white transition-all duration-300 ease-in-out',
            isOpen ? '-rotate-45 -translate-y-[15.8px] w-[40px]' : ''
        ]"></div>
    </button>
</template>

<script>
export default {
    props: {
        isOpen: {
            type: Boolean,
            default: false
        }
    }
};
</script>

// src/components/buttons/HamburgerMenu.tsx
import React from "react";

interface HamburgerMenuProps {
  isOpen: boolean;
  onClick?: () => void;
  className?: string; // Allow className prop
}

const HamburgerMenu: React.FC<HamburgerMenuProps> = ({
  isOpen,
  onClick,
  className = "",
}) => {
  return (
    <button
      aria-label="Hamburger Menu"
      className={`w-[32px] h-[32px] flex flex-col justify-between items-center relative ${className}`} // Add className here
      onClick={onClick}
    >
      {/* Top bar */}
      <div
        className={[
          "w-[32px] h-[4px] bg-white transition-all duration-150 ease-in-out",
          isOpen ? "rotate-45 translate-y-[14px] w-[40px]" : "",
        ].join(" ")}
      ></div>
      {/* Middle bar */}
      <div
        className={[
          "w-[32px] h-[4px] bg-white transition-all duration-150 ease-in-out",
          isOpen ? "opacity-0" : "",
        ].join(" ")}
      ></div>
      {/* Bottom bar */}
      <div
        className={[
          "w-[32px] h-[4px] bg-white transition-all duration-150 ease-in-out",
          isOpen ? "-rotate-45 -translate-y-[14px] w-[40px]" : "",
        ].join(" ")}
      ></div>
    </button>
  );
};

export default HamburgerMenu;
