// src/routes/uritused/[type]/+page.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import { page } from "$app/stores";
    import * as m from "$lib/paraglide/messages";
    import { getLocale } from "$lib/paraglide/runtime";
    import { getEventsByCategory, type Event } from "$lib/firebase";
    import SEO from "$lib/components/SEO.svelte";
    import Loading from "$lib/components/Loading.svelte";
    import PageHeader from "$lib/components/PageHeader.svelte";
    import ImageButton from "$lib/components/ImageButton.svelte";

    let events = $state<Event[]>([]);
    let loading = $state(true);
    let category = $derived($page.params.type ?? "");
    let isEnglish = $derived(getLocale() === "en");

    const categoryTitles: Record<
        string,
        { et: string; en: string; image: string }
    > = {
        haridus: {
            et: "Hariduslikud üritused",
            en: "Educational events",
            image: "/headers/haridus.jpg",
        },
        meelelahutus: {
            et: "Meelelahutuslikud üritused",
            en: "Entertainment events",
            image: "/headers/meelelahutus.jpg",
        },
        muu: {
            et: "Sise- ja muud üritused",
            en: "Internal and other events",
            image: "/headers/sisekad.jpg",
        },
    };

    onMount(async () => {
        try {
            if (category) events = await getEventsByCategory(category);
        } catch (error) {
            console.error("Error loading events:", error);
        } finally {
            loading = false;
        }
    });
</script>

<SEO pageKey="uritused" />

<div>
    <PageHeader
        title={categoryTitles[category]?.[isEnglish ? "en" : "et"] ?? category}
        backgroundImage={categoryTitles[category]?.image ||
            "/ituk_placeholder.jpg"}
    />

    {#if loading}
        <Loading fullHeight />
    {:else if events.length === 0}
        <div
            class="section-padding container-content flex flex-col items-center justify-center gap-8 min-h-[50vh]"
        >
            <p class="text-gray">{m.event_noyears()}</p>
        </div>
    {:else}
        <div class="section-padding container-content">
            <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
                {#each events as event (event.id)}
                    <a
                        href="/uritused/{event.category}/{event.handle}"
                        class="group relative rounded-lg overflow-hidden aspect-video"
                    >
                        <img
                            src={event.banner || "/ituk_placeholder.jpg"}
                            alt={isEnglish ? event.name_en : event.name}
                            class="w-full h-full object-cover transition-transform duration-300 group-hover:scale-105"
                        />
                        <div
                            class="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent"
                        ></div>
                        <div class="absolute bottom-0 left-0 right-0 p-4">
                            <h3 class="text-white font-bold text-lg">
                                {isEnglish ? event.name_en : event.name}
                            </h3>
                        </div>
                    </a>
                {/each}
            </div>
        </div>
    {/if}
</div>

// src/app/[locale]/uritused/[type]/page.tsx
"use client";

import { db } from "@/firebase";
import { collection, getDocs, query, where } from "firebase/firestore";
import { useEffect, useState, useCallback } from "react";
import { DocumentData } from "firebase/firestore";
import Link from "next/link";
import Loading from "@/components/animations/loading";

interface Event {
  key: string;
  handle: string;
  category: string;
  banner: string;
  name: string;
}

export default function EventType({
  params,
}: {
  params: Promise<{ type: string }>;
}) {
  const [events, setEvents] = useState<Event[]>([]);
  const [category, setCategory] = useState<string>("");

  const categoryTitles: Record<string, string> = {
    haridus: "Hariduslikud üritused",
    meelelahutus: "Meelelahutuslikud üritused",
    muu: "Sise- ja muud üritused",
  };

  const getEvents = useCallback(async () => {
    try {
      const resolvedParams = await params;
      setCategory(resolvedParams.type);

      const q = query(
        collection(db, "events"),
        where("category", "==", resolvedParams.type)
      );
      const querySnapshot = await getDocs(q);
      const fetchedEvents: Event[] = querySnapshot.docs.map((doc) => {
        const data = doc.data() as DocumentData;
        return {
          key: doc.id,
          handle: data.handle,
          category: data.category,
          banner: data.banner,
          name: data.name,
        };
      });
      setEvents(fetchedEvents);
    } catch (error) {
      console.error("Error getting events: ", error);
    }
  }, [params]);

  useEffect(() => {
    getEvents();
  }, [getEvents]);

  return (
    <div>
      <h1 className="hidden">{categoryTitles[category]}</h1>
      {events.length === 0 ? (
        <div className="main-min justify-center items-center flex-col flex gap-8">
          <h2>Laeb...</h2>
          <Loading />
        </div>
      ) : (
        <div
          className={`main-min ${events.length <= 3
            ? "items-start flex-col sm:flex-row flex"
            : "grid grid-cols-[repeat(auto-fit,minmax(100%,1fr))] sm:grid-cols-[repeat(auto-fit,minmax(33.3333%,1fr))]"
            }`}
        >
          {events.map((event) => {
            const linkClass =
              events.length <= 3
                ? "w-full sm:h-screen sm:w-1/3 justify-center items-center bg-center bg-cover flex-col flex"
                : "w-full sm:h-[calc(50vh-44px)] justify-center items-center bg-center bg-cover flex-col flex";

            return (
              <Link
                key={event.key}
                href={`/uritused/${event.category}/${event.handle}`}
                className={linkClass}
                style={{ backgroundImage: `url(${event.banner})` }}
              >
                <div className="triple-height sm:h-screen w-full bg-black/50 hover:bg-primary/50 transition-colors duration-150 ease-in-out justify-center items-center flex-row flex">
                  <h2 className="p-8 title text-center">{event.name}</h2>
                </div>
              </Link>
            );
          })}
        </div>
      )}
    </div>
  );
}
