// src/routes/uritused/+page.svelte
<script lang="ts">
    import * as m from "$lib/paraglide/messages";
    import SEO from "$lib/components/SEO.svelte";
    import ImageButton from "$lib/components/ImageButton.svelte";
</script>

<SEO pageKey="uritused" />

<div class="items-start flex-col sm:flex-row flex">
    <h1 class="hidden">Üritused</h1>
    <div class="w-full sm:w-1/3">
        <ImageButton
            href="/uritused/haridus"
            backgroundImage="/headers/haridus.jpg"
            title={m.events_education()}
        />
    </div>
    <div class="w-full sm:w-1/3">
        <ImageButton
            href="/uritused/meelelahutus"
            backgroundImage="/headers/meelelahutus.jpg"
            title={m.events_entertainment()}
        />
    </div>
    <div class="w-full sm:w-1/3">
        <ImageButton
            href="/uritused/muu"
            backgroundImage="/headers/sisekad.jpg"
            title={m.events_other()}
        />
    </div>
</div>

// synnipaev/src/app/uritused/page.tsx
import Link from "next/link";

export default function Home() {
    return(
        <div className="flex flex-row items-start h-screen">
           <Link className="flex flex-col justify-center items-center py-8 h-full w-full bg-center bg-[url('@/assets/images/events/meelelahutus.jpg')]" href="/uritused/meelelahutus" >
            <h1 className="title">Meelelahutus</h1>
           </Link>
           <Link className="flex flex-col justify-center items-center py-8 h-full w-full bg-center bg-[url('@/assets/images/events/haridus.jpg')]" href="/uritused/haridus" >
            <h1 className="title">Haridus</h1>
           </Link>
           <Link className="flex flex-col justify-center items-center py-8 h-full w-full bg-center bg-[url('@/assets/images/events/sisekad.jpg')]" href="/uritused/muu" >
            <h1 className="title">Sise- ja muud üritused</h1>
           </Link> 
        </div>
    )
}
