// synnipaev/src/app/uritused/[type]/page.tsx
"use client";

import { db } from "@/firebase";
import { collection, getDocs, query, where } from "firebase/firestore";
import { useEffect, useState } from "react";
import { DocumentData } from "firebase/firestore";
import Link from "next/link";

interface Event {
  key: string;
  handle: string;
  category: string;
  banner: string;
  name: string;
}

export default function Home({
  params,
}: {
  params: Promise<{ type: string }>;
}) {
  const [events, setEvents] = useState<Event[]>([]);

  const getEvents = async () => {
    try {
      const q = query(
        collection(db, "events"),
        where("category", "==", (await params).type)
      );
      const querySnapshot = await getDocs(q);
      const events: Event[] = querySnapshot.docs.map((doc) => {
        const data = doc.data() as DocumentData;
        return {
          key: doc.id,
          handle: data.handle,
          category: data.category,
          banner: data.banner,
          name: data.name,
        };
      });
      setEvents(events);
    } catch (error) {
      console.error("Error getting members: ", error);
      throw error;
    }
  };

  useEffect(() => {
    console.log("ABCDEFG");
    getEvents();
  }, []);

  if (events.length === 0) {
    <div className="main-height items-start flex-row flex">
      <h2>No events found!</h2>
    </div>;
  }

  if (events.length <= 3) {
    return (
      <div className="grid min-w-full grid-cols-[repeat(auto-fit,minmax(33.33%,1fr))]">
        {events.map((event, index) => (
          <div
            id={index.toString()}
            className="main-height justify-center items-center bg-center bg-cover bg-[url('@/assets/images/events/sisekad.jpg')] flex-col flex"
            style={{ backgroundImage: `url(${event.banner})` }}
          >
            <div className="main-height w-full bg-black/50 hover:bg-primary/50 transition-colors duration-150 ease-in-out justify-center items-center flex-row flex">
              <h2 className="title text-center">{event.name}</h2>
            </div>
          </div>
        ))}
      </div>
    );
  } else {
    return (
      <div className="grid min-w-full grid-cols-[repeat(auto-fit,minmax(33.33%,1fr))]">
        {events.map((event, index) => (
          <Link
            href={"/uritused/" + event.category + "/" + event.handle}
            id={index.toString()}
            className="event-height justify-center items-center bg-center bg-cover bg-[url('@/assets/images/events/sisekad.jpg')] flex-col flex"
            style={{ backgroundImage: `url(${event.banner})` }}
          >
            <div className="event-height w-full bg-black/50 hover:bg-primary/50 transition-colors duration-150 ease-in-out justify-center items-center flex-row flex">
              <h2 className="title text-center">{event.name}</h2>
            </div>
          </Link>
        ))}
      </div>
    );
  }
}

// ituk.ee/src/routes/uritused/[type]/+page.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import { page } from "$app/stores";
    import * as m from "$lib/paraglide/messages";
    import { getLocale } from "$lib/paraglide/runtime";
    import { getEventsByCategory, type Event } from "$lib/firebase";
    import SEO from "$lib/components/SEO.svelte";
    import Loading from "$lib/components/Loading.svelte";
    import ImageButton from "$lib/components/ImageButton.svelte";

    let events = $state<Event[]>([]);
    let loading = $state(true);
    let category = $derived($page.params.type ?? "");
    let isEnglish = $derived(getLocale() === "en");

    const categoryTitles: Record<string, { et: string; en: string }> = {
        haridus: { et: "Hariduslikud üritused", en: "Educational events" },
        meelelahutus: {
            et: "Meelelahutuslikud üritused",
            en: "Entertainment events",
        },
        muu: { et: "Sise- ja muud üritused", en: "Internal and other events" },
    };

    onMount(async () => {
        try {
            if (category) events = await getEventsByCategory(category);
        } catch (error) {
            console.error("Error loading events:", error);
        } finally {
            loading = false;
        }
    });
</script>

<SEO pageKey="uritused" />

<h1 class="hidden">
    {categoryTitles[category]?.[isEnglish ? "en" : "et"] ?? category}
</h1>

{#if loading}
    <div class="flex flex-col items-center justify-center gap-8 min-h-[50vh]">
        <h2>Laeb...</h2>
        <Loading />
    </div>
{:else if events.length === 0}
    <div class="flex flex-col items-center justify-center gap-8 min-h-[50vh]">
        <p class="text-gray">{m.event_noyears()}</p>
    </div>
{:else}
    <div
        class={events.length <= 3
            ? "items-start flex-col sm:flex-row flex"
            : "grid grid-cols-1 sm:grid-cols-3"}
    >
        {#each events as event (event.id)}
            <div class={events.length <= 3 ? "w-full sm:w-1/3" : "w-full"}>
                <ImageButton
                    href="/uritused/{event.category}/{event.handle}"
                    backgroundImage={event.banner}
                    title={isEnglish ? event.name_en : event.name}
                    height={events.length <= 3 ? "full" : "half"}
                />
            </div>
        {/each}
    </div>
{/if}
