// ituk.ee/src/lib/components/Footer.svelte
<script lang="ts">
	import * as m from "$lib/paraglide/messages";

	const currentYear = new Date().getFullYear();
</script>

<footer
	class="z-50 w-full py-[clamp(2rem,4vw,4rem)] px-[clamp(1rem,4vw,4rem)] bg-background shadow-filled flex flex-col sm:flex-row flex-wrap justify-between items-center gap-8 sm:gap-16"
>
	<!-- Contact Info -->
	<div class="flex flex-col gap-4 items-start">
		<div class="flex items-center gap-2">
			<span class="material-symbols-outlined text-white text-xl"
				>mail</span
			>
			<a
				href="mailto:kontakt@ituk.ee"
				class="font-bold underline hover:decoration-primary"
			>
				kontakt@ituk.ee
			</a>
		</div>
		<div class="flex items-center gap-2">
			<span class="material-symbols-outlined text-white text-xl"
				>call</span
			>
			<a
				href="tel:+37258517633"
				class="font-bold underline hover:decoration-primary"
			>
				+372 5851 7633
			</a>
		</div>
		<div class="flex items-center gap-2">
			<span class="material-symbols-outlined text-white text-xl"
				>location_on</span
			>
			<a
				href="https://www.google.com/maps/place/TalTech+IT+College/@59.3954482,24.6617187,17z"
				class="font-bold underline hover:decoration-primary"
			>
				ICO-210, Raja 4c, Tallinn
			</a>
		</div>
	</div>

	<!-- Organization Data -->
	<div class="flex flex-col gap-4 items-center text-center">
		<p class="font-bold">MTÜ FOR Tsükkel</p>
		<p class="font-bold">Registrikood: 80391807</p>
		<p class="font-bold">LHV EE617700771002582855</p>
	</div>

	<!-- Social Media & Links -->
	<div class="flex flex-col gap-4 items-end">
		<div class="flex items-center gap-6">
			<a
				href="https://www.facebook.com/ituk.taltech/"
				target="_blank"
				rel="noopener noreferrer"
				aria-label="Facebook"
			>
				<img
					src="/icons/facebook.svg"
					alt="Facebook"
					class="w-6 h-6 hover:opacity-80 transition-opacity"
				/>
			</a>
			<div class="w-[2px] h-6 bg-white"></div>
			<a
				href="https://www.instagram.com/ituk.taltech/"
				target="_blank"
				rel="noopener noreferrer"
				aria-label="Instagram"
			>
				<img
					src="/icons/instagram.svg"
					alt="Instagram"
					class="w-6 h-6 hover:opacity-80 transition-opacity"
				/>
			</a>
			<div class="w-[2px] h-6 bg-white"></div>
			<a
				href="https://www.github.com/ituk-ttu/"
				target="_blank"
				rel="noopener noreferrer"
				aria-label="GitHub"
			>
				<img
					src="/icons/github.svg"
					alt="GitHub"
					class="w-6 h-6 hover:opacity-80 transition-opacity"
				/>
			</a>
		</div>
		<div class="flex items-center justify-between w-full gap-6">
			<a
				href="https://hub.ituk.ee/"
				target="_blank"
				rel="noopener noreferrer"
				class="font-bold underline hover:decoration-primary"
			>
				HUB
			</a>
			<a
				href="/stiil"
				class="font-bold underline hover:decoration-primary"
			>
				{m.footer_style()}
			</a>
		</div>
		<div class="flex items-center gap-2">
			<span class="material-symbols-outlined text-white text-base"
				>copyright</span
			>
			<p class="font-bold">ITÜK 2017-{currentYear}</p>
		</div>
	</div>
</footer>

// src/components/Footer.jsx
import React from "react";
import "./Footer.css";
import { MdEmail } from "react-icons/md";
import { MdLocationPin } from "react-icons/md";


const Footer = () => {
  return (
    <div className="footer">
      <div className="container">
        {/* <div class="flex mt-4 space-x-10  sm:justify-center sm:mt-0"> */}
        <div class="grid grid-cols-1 sm:grid-cols-1 gap-4 md:grid-cols-1 lg:grid-cols-3 xl:grid-cols-3">
          <div class="grid col-span-1 justify-center place-items-center">
            <li>
              <MdLocationPin />
              <p>Raja 4c, Tallinn, Harjumaa 12616</p>
            </li>
          </div>
          <div class="grid col-span-1 justify-center place-items-center ">
            <li>
              <MdEmail />
              <a
                href="mailto:kontakt@ituk.ee"
                class="text-white hover:text-[#870042]"
              >
                kontakt@ituk.ee
              </a>
            </li>
          </div>
          <div class="flex col-span-1  justify-center place-items-center gap-6">
            <a
              href="https://hub.ituk.ee"
              class="text-white hover:text-[#870042]" 
              target="_blank" 
              rel="noopener noreferrer"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                class="h-10 w-10"
                viewBox="0 0 20 20"
                fill="currentColor"
              >
                <path
                  fill-rule="evenodd"
                  d="M2 5a2 2 0 012-2h12a2 2 0 012 2v10a2 2 0 01-2 2H4a2 2 0 01-2-2V5zm3.293 1.293a1 1 0 011.414 0l3 3a1 1 0 010 1.414l-3 3a1 1 0 01-1.414-1.414L7.586 10 5.293 7.707a1 1 0 010-1.414zM11 12a1 1 0 100 2h3a1 1 0 100-2h-3z"
                  clip-rule="evenodd"
                />
              </svg>
              <span class="sr-only">Hub page</span>
            </a>
            <a
              href="https://facebook.com/ituk.taltech"
              class="text-white hover:text-[#870042]" 
              target="_blank" 
              rel="noopener noreferrer"
            >
              <svg
                class="w-10 h-10"
                fill="currentColor"
                viewBox="0 0 24 24"
                aria-hidden="true"
              >
                <path
                  fill-rule="evenodd"
                  d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z"
                  clip-rule="evenodd"
                />
              </svg>
              <span class="sr-only">Facebook page</span>
            </a>
            <a
              href="https://www.instagram.com/ituk.taltech"
              class="text-white hover:text-[#870042] dark:hover:text-white" 
              target="_blank" 
              rel="noopener noreferrer"
            >
              <svg
                class="w-10 h-10"
                fill="currentColor"
                viewBox="0 0 24 24"
                aria-hidden="true"
              >
                <path
                  fill-rule="evenodd"
                  d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z"
                  clip-rule="evenodd"
                />
              </svg>
              <span class="sr-only">Instagram page</span>
            </a>
            <a
              href="https://www.github.com/ituk-ttu"
              class="text-white hover:text-[#870042] dark:hover:text-white" 
              target="_blank" 
              rel="noopener noreferrer"
            >
              <svg
                class="w-10 h-10"
                fill="currentColor"
                viewBox="0 0 24 24"
                aria-hidden="true"
              >
                <path
                  fill-rule="evenodd"
                  d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
                  clip-rule="evenodd"
                />
              </svg>
              <span class="sr-only">GitHub account</span>
            </a>
          </div>
        </div>
        <span className="line"></span>
        <p>&copy; {new Date().getFullYear()} IT-teaduskonna üliõpilaskogu</p>
      </div>
    </div>
  );
};

export default Footer;
