// synnipaev/src/components/footer.tsx
import React from "react";
import email from "@/assets/icons/email.svg";
import phone from "@/assets/icons/phone.svg";
import location from "@/assets/icons/location.svg";
import hub from "@/assets/logos/ituk_hub.svg";
import Image from "next/image";
import Link from "next/link";
import FacebookLink from "./buttons/socials/Facebook";
import InstagramLink from "./buttons/socials/Instagram";
import GitHubLink from "./buttons/socials/Github";

export default function Footer() {
  return (
    <footer className="main-container main-padding dark shadow-filled justify-between items-center flex-col gap-auto md:flex-row gap-32 md:gap-auto flex">
      <div className="justify-between items-start gap-8 flex-col flex">
        <div className="justify-start items-center gap-4 flex-row flex">
          <Image src={email} alt="E-mail" />
          <p className="font-bold underline">kontakt@ituk.ee</p>
        </div>
        <div className="justify-start items-center gap-4 flex-row flex">
          <Image src={phone} alt="Phone number" />
          <p className="font-bold underline">+372 5693 1193</p>
        </div>
        <div className="justify-start items-center gap-4 flex-row flex">
          <Image src={location} alt="Our office" />
          <p className="font-bold underline">
            ICO-210, Raja 4c, Tallinn, Harjumaa
          </p>
        </div>
      </div>
      <div className="justify-between items-center md:items-end gap-8 flex-col flex">
        <div className="justify-between items-center gap-6 flex-row flex">
          <FacebookLink />
          <div className="w-[2px] h-[24px] bg-light" />
          <InstagramLink />
          <div className="w-[2px] h-[24px] bg-light" />
          <GitHubLink />
        </div>
        <div className="justify-between items-center gap-6 flex-row flex">
          <Link href="https://hub.ituk.ee/">
            <Image src={hub} alt="Hub" />
          </Link>
          <Link href="/stiil">
            <p className="font-bold underline">Stiiliraamat</p>
          </Link>
        </div>
        <p className="font-bold">© ITÜK 2016-2024</p>
      </div>
    </footer>
  );
}

// ituk.ee/src/lib/components/Footer.svelte
<script lang="ts">
	import * as m from "$lib/paraglide/messages";

	const currentYear = new Date().getFullYear();
</script>

<footer
	class="z-50 w-full py-[clamp(2rem,4vw,4rem)] px-[clamp(1rem,4vw,4rem)] bg-background shadow-filled flex flex-col sm:flex-row flex-wrap justify-between items-center gap-8 sm:gap-16"
>
	<!-- Contact Info -->
	<div class="flex flex-col gap-4 items-start">
		<div class="flex items-center gap-2">
			<span class="material-symbols-outlined text-white text-xl"
				>mail</span
			>
			<a
				href="mailto:kontakt@ituk.ee"
				class="font-bold underline hover:decoration-primary"
			>
				kontakt@ituk.ee
			</a>
		</div>
		<div class="flex items-center gap-2">
			<span class="material-symbols-outlined text-white text-xl"
				>call</span
			>
			<a
				href="tel:+37258517633"
				class="font-bold underline hover:decoration-primary"
			>
				+372 5851 7633
			</a>
		</div>
		<div class="flex items-center gap-2">
			<span class="material-symbols-outlined text-white text-xl"
				>location_on</span
			>
			<a
				href="https://www.google.com/maps/place/TalTech+IT+College/@59.3954482,24.6617187,17z"
				class="font-bold underline hover:decoration-primary"
			>
				ICO-210, Raja 4c, Tallinn
			</a>
		</div>
	</div>

	<!-- Organization Data -->
	<div class="flex flex-col gap-4 items-center text-center">
		<p class="font-bold">MTÜ FOR Tsükkel</p>
		<p class="font-bold">Registrikood: 80391807</p>
		<p class="font-bold">LHV EE617700771002582855</p>
	</div>

	<!-- Social Media & Links -->
	<div class="flex flex-col gap-4 items-end">
		<div class="flex items-center gap-6">
			<a
				href="https://www.facebook.com/ituk.taltech/"
				target="_blank"
				rel="noopener noreferrer"
				aria-label="Facebook"
			>
				<img
					src="/icons/facebook.svg"
					alt="Facebook"
					class="w-6 h-6 hover:opacity-80 transition-opacity"
				/>
			</a>
			<div class="w-[2px] h-6 bg-white"></div>
			<a
				href="https://www.instagram.com/ituk.taltech/"
				target="_blank"
				rel="noopener noreferrer"
				aria-label="Instagram"
			>
				<img
					src="/icons/instagram.svg"
					alt="Instagram"
					class="w-6 h-6 hover:opacity-80 transition-opacity"
				/>
			</a>
			<div class="w-[2px] h-6 bg-white"></div>
			<a
				href="https://www.github.com/ituk-ttu/"
				target="_blank"
				rel="noopener noreferrer"
				aria-label="GitHub"
			>
				<img
					src="/icons/github.svg"
					alt="GitHub"
					class="w-6 h-6 hover:opacity-80 transition-opacity"
				/>
			</a>
		</div>
		<div class="flex items-center justify-between w-full gap-6">
			<a
				href="https://hub.ituk.ee/"
				target="_blank"
				rel="noopener noreferrer"
				class="font-bold underline hover:decoration-primary"
			>
				HUB
			</a>
			<a
				href="/stiil"
				class="font-bold underline hover:decoration-primary"
			>
				{m.footer_style()}
			</a>
		</div>
		<div class="flex items-center gap-2">
			<span class="material-symbols-outlined text-white text-base"
				>copyright</span
			>
			<p class="font-bold">ITÜK 2017-{currentYear}</p>
		</div>
	</div>
</footer>
