// src/components/statistics.tsx
"use client";

import { useEffect, useRef, useState } from "react";

interface StatItemProps {
    value: string;
    label: string;
}

function StatItem({ value, label }: StatItemProps) {
    const [displayValue, setDisplayValue] = useState("0");
    const [hasAnimated, setHasAnimated] = useState(false);
    const ref = useRef<HTMLDivElement>(null);

    // Parse number and suffix (e.g., "500+" -> { num: 500, suffix: "+" })
    const match = value.match(/^(\d+)(.*)$/);
    const targetNum = match ? parseInt(match[1], 10) : 0;
    const suffix = match ? match[2] : "";

    useEffect(() => {
        const element = ref.current;
        if (!element) return;

        const observer = new IntersectionObserver(
            (entries) => {
                if (entries[0].isIntersecting && !hasAnimated) {
                    setHasAnimated(true);

                    const duration = 1500; // ms
                    const startTime = performance.now();

                    const animate = (currentTime: number) => {
                        const elapsed = currentTime - startTime;
                        const progress = Math.min(elapsed / duration, 1);

                        // Ease-out curve for smoother ending
                        const easeOut = 1 - Math.pow(1 - progress, 3);
                        const current = Math.floor(easeOut * targetNum);

                        setDisplayValue(current.toString());

                        if (progress < 1) {
                            requestAnimationFrame(animate);
                        } else {
                            setDisplayValue(targetNum.toString());
                        }
                    };

                    requestAnimationFrame(animate);
                }
            },
            { threshold: 0.5 }
        );

        observer.observe(element);
        return () => observer.disconnect();
    }, [targetNum, hasAnimated]);

    return (
        <div ref={ref} className="flex flex-col items-center gap-2 min-w-24 transition-transform duration-150 hover:scale-110">
            {/* Invisible element to reserve space for final value */}
            <span className="text-stat font-bold relative">
                <span className="invisible">{value}</span>
                <span className="absolute inset-0 flex justify-center">{displayValue}{suffix}</span>
            </span>
            <span className="text-center">{label}</span>
        </div>
    );
}

interface StatisticsProps {
    items: StatItemProps[];
    title?: string;
}

export default function Statistics({ items, title }: StatisticsProps) {
    return (
        <div className="section-padding bg-primary">
            <div className="container-content flex flex-col lg:flex-row justify-between items-center gap-8">
                {title && <h2 className="shrink-0">{title}</h2>}
                <div className="flex flex-wrap justify-center items-center gap-16">
                    {items.map((item, index) => (
                        <StatItem key={index} value={item.value} label={item.label} />
                    ))}
                </div>
            </div>
        </div>
    );
}

export { StatItem };
export type { StatItemProps, StatisticsProps };

// ituk.ee/src/lib/components/Statistics.svelte
<script lang="ts">
    import { onMount } from "svelte";

    interface StatItem {
        value: string;
        label: string;
    }

    interface Props {
        title: string;
        items: StatItem[];
    }

    let { title, items }: Props = $props();
    let containerRef: HTMLElement;
    let displayValues = $state<string[]>([]);
    let hasAnimated = $state(false);

    $effect(() => {
        if (displayValues.length === 0 && items.length > 0) {
            displayValues = items.map(() => "0");
        }
    });

    function parseValue(value: string): { num: number; suffix: string } {
        const match = value.match(/^(\d+)(.*)$/);
        if (match) {
            return { num: parseInt(match[1], 10), suffix: match[2] };
        }
        return { num: 0, suffix: value };
    }

    function animateCount(
        index: number,
        targetNum: number,
        suffix: string,
        duration: number = 2000,
    ) {
        const startTime = performance.now();
        const startValue = 0;

        function update(currentTime: number) {
            const elapsed = currentTime - startTime;
            const progress = Math.min(elapsed / duration, 1);
            const easeOut = 1 - Math.pow(1 - progress, 3);
            const currentValue = Math.round(
                startValue + (targetNum - startValue) * easeOut,
            );

            displayValues[index] = currentValue + suffix;

            if (progress < 1) {
                requestAnimationFrame(update);
            }
        }

        requestAnimationFrame(update);
    }

    onMount(() => {
        const observer = new IntersectionObserver(
            (entries) => {
                entries.forEach((entry) => {
                    if (entry.isIntersecting && !hasAnimated) {
                        hasAnimated = true;
                        items.forEach((item, index) => {
                            const { num, suffix } = parseValue(item.value);
                            if (num > 0) {
                                animateCount(index, num, suffix);
                            } else {
                                displayValues[index] = item.value;
                            }
                        });
                    }
                });
            },
            { threshold: 0.2 },
        );

        if (containerRef) {
            observer.observe(containerRef);
        }

        return () => observer.disconnect();
    });
</script>

<div
    bind:this={containerRef}
    class="section-padding bg-primary container-content flex flex-col md:flex-row justify-between items-center gap-8"
>
    <h2 class="text-center md:text-left">{title}</h2>
    <div class="flex flex-wrap justify-center md:justify-end gap-8">
        {#each items as item, index}
            <div class="flex flex-col items-center gap-2">
                <span class="text-stat font-bold">{displayValues[index]}</span>
                <span class="text-center text-stat-label">{item.label}</span>
            </div>
        {/each}
    </div>
</div>
