// ituk/src/components/cards/GalleryCard.vue
<script setup lang="ts">
const props = defineProps({
    index: {
        type: Number,
        required: true,
    },
    imageSrc: {
        type: String,
        required: true,
    },
    cardName: {
        type: String,
        required: true,
    },
});

const emit = defineEmits(['open-overlay']);

const handleClick = () => {
    emit('open-overlay', props.index);
};
</script>

<template>
    <button @click="handleClick"
        class="w-full h-full max-h-56 flex-col justify-center items-center flex relative shadow-card">
        <img class="w-full h-full aspect-video object-cover" :src="imageSrc" :alt="cardName" />
    </button>
</template>

// src/components/gallery/gallery-card.tsx
import React from 'react';

interface GalleryCardProps {
    index: number;
    imageSrc: string;
    cardName: string;
    onOpenOverlay: (index: number) => void;
}

const GalleryCard: React.FC<GalleryCardProps> = ({ index, imageSrc, cardName, onOpenOverlay }) => {
    return (
        <button
            className="w-full h-full max-h-56 flex-col justify-center items-center flex relative shadow-filled"
            onClick={() => onOpenOverlay(index)}
            aria-label={`Open ${cardName}`}
        >
            <img className="w-full h-full aspect-video object-cover" src={imageSrc} alt={cardName} />
        </button>
    );
};

export default GalleryCard;
