// src/app/[locale]/rent/page.tsx
"use client";

import { db } from '@/firebase';
import { collection, getDocs, query } from 'firebase/firestore';
import { useEffect, useState } from 'react';
import { DocumentData } from 'firebase/firestore';
import Card from "@/components/cards/card";
import { useDictionary } from '@/components/dictionary-provider';
import { usePathname } from 'next/navigation';
import PageHeader from "@/components/page-header";

interface Rent {
  name: string;
  en_name: string;
  price: number;
  unit: string;
  imagePath: string;
}

export default function Home() {
  const pathname = usePathname();
  const currentLocale = pathname?.split("/")[1];

  //get dictionary
  const dictionary = useDictionary().rent;

  const [rentables, setRentables] = useState<Rent[]>([]);

  const getRentables = async () => {
    try {
      const querySnapshot = await getDocs(
        query(collection(db, "rent"))
      );
      const rent: Rent[] = querySnapshot.docs.map((doc) => {
        const data = doc.data() as DocumentData;
        return {
          name: data.name,
          en_name: data.name_en,
          price: data.price,
          unit: data.unit,
          imagePath: data.imagePath,
        };
      });
      setRentables(rent);
    } catch (error) {
      console.error('Error getting members: ', error);
      throw error;
    }
  };

  useEffect(() => {
    getRentables();
  }, []);

  return (
    <div>
      <PageHeader title={dictionary.header} backgroundImage="/headers/rent.jpg" />

      <div className="section-padding container-content gap-16 flex-col lg:flex-row flex">
        <div className="w-full lg:w-1/3 flex flex-col gap-8">
          <h2>{dictionary.title}</h2>
          <p>{dictionary.description}</p>
          <p>{dictionary.request}<a className="font-bold underline hover:text-primary" href="mailto:kontakt@ituk.ee?subject=Tehnika rent - [ürituse nimi]&body=Tervist,%0A%0ASoovin rentida tehnikat üritusele [ürituse nimi] kuupäevadel [kuupäev].%0A%0ALugupidamisega">kontakt@ituk.ee</a></p>
          <p className="text-sm text-gray">{dictionary.NB}</p>
        </div>

        <div className="w-full lg:w-2/3 grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-8">
          {rentables.map((rent, index) => (
            <Card key={index} title={currentLocale === "en" ? rent.en_name : rent.name} image={rent.imagePath} listItems={[rent.price.toString() + " " + rent.unit]} type="list" />
          ))}
        </div>
      </div>
    </div>
  )
}

// ituk.ee/src/routes/rent/+page.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import * as m from "$lib/paraglide/messages";
    import { getLocale } from "$lib/paraglide/runtime";
    import PageHeader from "$lib/components/PageHeader.svelte";
    import Card from "$lib/components/Card.svelte";
    import { getRentItems, type RentItem } from "$lib/firebase";
    import SEO from "$lib/components/SEO.svelte";

    let rentItems = $state<RentItem[]>([]);
    let loading = $state(true);
    let error = $state<string | null>(null);

    onMount(async () => {
        try {
            rentItems = await getRentItems();
        } catch (e) {
            console.error("Error loading rent items:", e);
            error = "Failed to load rental items";
        } finally {
            loading = false;
        }
    });

    function getLocalizedName(item: RentItem): string {
        return getLocale() === "en" && item.name_en ? item.name_en : item.name;
    }
</script>

<SEO pageKey="rent" />

<div>
    <PageHeader title={m.rent_header()} backgroundImage="/headers/rent.jpg" />

    <div class="section-padding container-content flex flex-col gap-8">
        <h2>{m.rent_title()}</h2>
        <p>{m.rent_description()}</p>
        <p>
            {m.rent_request()}
            <a
                class="text-primary underline hover:brightness-125"
                href="mailto:kontakt@ituk.ee">kontakt@ituk.ee</a
            >
        </p>
        <p class="text-primary font-bold">{m.rent_NB()}</p>

        {#if loading}
            <p class="text-gray">{m.common_loading()}</p>
        {:else if error}
            <p class="text-red-500">{error}</p>
        {:else if rentItems.length === 0}
            <p class="text-gray">No rental items available</p>
        {:else}
            <div
                class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8 justify-items-center"
            >
                {#each rentItems as item}
                    <Card
                        title={getLocalizedName(item)}
                        image={item.imagePath}
                        listItems={[`${item.price} ${item.unit}`]}
                        type="list"
                    />
                {/each}
            </div>
        {/if}
    </div>
</div>
