// src/app/[locale]/uritused/[type]/[event]/page.tsx
"use client";

import { useEffect, useState } from "react";
import { db } from "@/firebase";
import { query, collection, where, getDocs, DocumentData, doc, orderBy } from "firebase/firestore";
import Loading from "@/components/animations/loading";
import Card from "@/components/cards/card";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useDictionary } from "@/components/dictionary-provider";

interface Event {
  category: string;
  banner: string;
  name: string;
  en_name: string;
  description: string;
  en_description: string;
  gallery?: { src: string; name: string }[];
  links?: Map<string, Map<string, string>>;
}

interface EventYear {
  key: string;
  banner: string;
  date: string;
  description: string;
  extraInformation?: string;
  handle: string;
  gallery?: Map<string, string>;
  title: string;
}

export default function EventPage({
  params: paramsPromise,
}: {
  params: Promise<{ event: string }>;
}) {
  const pathname = usePathname();
  const currentLocale = pathname?.split("/")[1];

  const dictionary = useDictionary().event;

  const [curEvent, setCurEvent] = useState<Event | null>(null);
  const [eventHandle, setEventHandle] = useState<string | null>(null);
  const [eventYears, setEventYears] = useState<EventYear[]>([]);
  const [images, setImages] = useState<Map<string, string>>();

  useEffect(() => {
    async function unwrapParams() {
      const params = await paramsPromise;
      setEventHandle(params.event);
    }
    unwrapParams();
  }, [paramsPromise]);

  const getEvent = async () => {
    if (!eventHandle) return;

    try {
      const q = query(
        collection(db, "events"),
        where("handle", "==", eventHandle)
      );
      const querySnapshot = await getDocs(q);

      const events: Event[] = querySnapshot.docs.map((doc) => {
        const data = doc.data() as DocumentData;

        const gallery = data.gallery
          ? (data.gallery as string[]).map((src: string, index: number) => ({
            src,
            name: `Image ${index + 1}`,
          }))
          : undefined;

        const links =
          data.links && typeof data.links === "object"
            ? new Map(
              Object.entries(data.links).map(([year, events]) => [
                year,
                new Map(
                  Object.entries(events as Record<string, string>)
                ),
              ])
            )
            : undefined;

        return {
          category: data.category,
          banner: data.banner,
          name: data.name,
          en_name: data.name_en,
          description: data.description,
          en_description: data.description_en,
          gallery,
          links,
        };
      });

      try {
        const eventRef = doc(db, "events", querySnapshot.docs[0].id);
        const yearQuerySnapshot = await getDocs(
          query(collection(eventRef, "years"), orderBy("date", "desc"))
        );
        const _eventYears: EventYear[] = yearQuerySnapshot.docs.map((doc) => {
          const data = doc.data() as DocumentData;
          return {
            key: doc.id,
            banner: data.banner,
            date: data.date,
            description: data.description,
            gallery: data.gallery ? data.gallery : undefined,
            handle: data.handle,
            title: data.title
          };
        });
        setEventYears(_eventYears);
      } catch (error) {
        console.error("Error getting members: ", error);
      }

      setCurEvent(events[0]);
      getImages();
    } catch (error) {
      console.error("Error getting event: ", error);
    }
  };

  const getImages = () => (
    eventYears.map((year) => (
      year.gallery?.forEach((title, image) => {
        const newMap = new Map(images);
        newMap.set(title, image)
        setImages(newMap)
        console.log(images)
      }
      ))
    ))

  useEffect(() => {
    getEvent();
  }, [getEvent]);

  if (curEvent) {
    return (
      <div className="main-min">
        <div className="flex flex-col items-center">
          <div
            className="items-center justify-center h-full w-full bg-center bg-cover flex-row flex"
            style={{ backgroundImage: `url(${curEvent.banner})` }}
          >
            <div className="main-padding w-full bg-black/50 justify-center items-center flex-row flex">
              <h1 className="big text-center">{currentLocale === "en" ? curEvent.en_name : curEvent.name}</h1>
            </div>
          </div>

          <div className="main-padding w-full justify-center items-start flex-col flex gap-16">
            <div className="w-full justify-start items-start flex-col md:flex-row flex gap-16">
              <div className="w-full justify-center items-start flex-col flex gap-16">
                <h2>{dictionary.description}</h2>
                <div>
                  {(currentLocale === "en" ? curEvent?.en_description : curEvent?.description)
                    ?.split("\n")
                    .map((line, index) => (
                      <p key={index}>
                        {line}
                        <br />
                        <br />
                      </p>
                    ))}
                </div>

              </div>
            </div>

            {eventYears ? (
              <div className="w-full justify-center items-start flex-col flex gap-8">
                <h2>{dictionary.years}</h2>
                <div className="grid min-w-full grid-cols-1 gap-8 xs:grid-cols-2 lg:grid-cols-4">
                  {eventYears.map((year) => (
                    <Link key={year.key} href={`${pathname}/${year.handle}`}>
                      <Card title={year.title} image={year.banner} type="default" />
                    </Link>
                  ))}
                </div>
              </div>
            ) : (
              <div className="w-full justify-center items-start flex-col flex gap-8">
                <h2>{dictionary.years}</h2>
                <p className="italic">{dictionary.noyears}</p>
              </div>
            )}

            <div className="justify-center items-center flex-col sm:flex-row flex gap-16">
              {images && Array.from(images.entries()).map(([title, image], index) => (
                <div key={index}>
                  <img src={image} alt={title} />
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="main-min justify-center items-center flex-col flex gap-8">
      <h2>Laeb...</h2>
      <Loading />
    </div>
  );
}

// ituk.ee/src/routes/uritused/[type]/[event]/+page.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import { page } from "$app/stores";
    import * as m from "$lib/paraglide/messages";
    import { getLocale } from "$lib/paraglide/runtime";
    import {
        getEventByHandle,
        getEventYears,
        type Event,
        type EventYear,
    } from "$lib/firebase";
    import SEO from "$lib/components/SEO.svelte";
    import Loading from "$lib/components/Loading.svelte";
    import Card from "$lib/components/Card.svelte";

    let event = $state<Event | null>(null);
    let eventYears = $state<EventYear[]>([]);
    let loading = $state(true);
    let eventHandle = $derived($page.params.event ?? "");
    let eventType = $derived($page.params.type ?? "");
    let isEnglish = $derived(getLocale() === "en");

    onMount(async () => {
        try {
            if (eventHandle) event = await getEventByHandle(eventHandle);
            if (event?.id) {
                eventYears = await getEventYears(event.id);
            }
        } catch (error) {
            console.error("Error loading event:", error);
        } finally {
            loading = false;
        }
    });
</script>

<SEO pageKey="uritused" />

{#if loading}
    <div class="flex flex-col items-center justify-center gap-8 min-h-[50vh]">
        <h2>Laeb...</h2>
        <Loading />
    </div>
{:else if event}
    <div class="flex flex-col items-center">
        <div
            class="items-center justify-center h-full w-full bg-center bg-cover flex-row flex"
            style="background-image: url({event.banner})"
        >
            <div
                class="section-padding w-full bg-black/50 justify-center items-center flex-row flex"
            >
                <h1 class="text-big text-center">
                    {isEnglish ? event.name_en : event.name}
                </h1>
            </div>
        </div>

        <div
            class="section-padding container-content justify-center items-start flex-col flex gap-16"
        >
            <div
                class="w-full justify-start items-start flex-col md:flex-row flex gap-16"
            >
                <div
                    class="w-full justify-center items-start flex-col flex gap-16"
                >
                    <h2>{m.event_description()}</h2>
                    <div>
                        {#each (isEnglish ? event.description_en : event.description)?.split("\n") ?? [] as line, index}
                            <p>
                                {line}
                                <br /><br />
                            </p>
                        {/each}
                    </div>
                </div>
            </div>

            {#if eventYears.length > 0}
                <div
                    class="w-full justify-center items-start flex-col flex gap-8"
                >
                    <h2>{m.event_years()}</h2>
                    <div
                        class="grid min-w-full grid-cols-1 gap-8 xs:grid-cols-2 lg:grid-cols-4"
                    >
                        {#each eventYears as year (year.id)}
                            <a
                                href="/uritused/{eventType}/{eventHandle}/{year.handle}"
                            >
                                <Card
                                    title={isEnglish
                                        ? year.title_en
                                        : year.title}
                                    image={year.banner}
                                    type="default"
                                />
                            </a>
                        {/each}
                    </div>
                </div>
            {:else}
                <div
                    class="w-full justify-center items-start flex-col flex gap-8"
                >
                    <h2>{m.event_years()}</h2>
                    <p class="italic text-gray">{m.event_noyears()}</p>
                </div>
            {/if}
        </div>
    </div>
{:else}
    <div class="flex flex-col items-center justify-center gap-8 min-h-[50vh]">
        <p class="text-gray">Event not found</p>
    </div>
{/if}
