// synnipaev/src/components/footer.tsx
import React from "react";
import email from "@/assets/icons/email.svg";
import phone from "@/assets/icons/phone.svg";
import location from "@/assets/icons/location.svg";
import hub from "@/assets/logos/ituk_hub.svg";
import Image from "next/image";
import Link from "next/link";
import FacebookLink from "./buttons/socials/Facebook";
import InstagramLink from "./buttons/socials/Instagram";
import GitHubLink from "./buttons/socials/Github";

export default function Footer() {
  return (
    <footer className="main-container main-padding dark shadow-filled justify-between items-center flex-col gap-auto md:flex-row gap-32 md:gap-auto flex">
      <div className="justify-between items-start gap-8 flex-col flex">
        <div className="justify-start items-center gap-4 flex-row flex">
          <Image src={email} alt="E-mail" />
          <p className="font-bold underline">kontakt@ituk.ee</p>
        </div>
        <div className="justify-start items-center gap-4 flex-row flex">
          <Image src={phone} alt="Phone number" />
          <p className="font-bold underline">+372 5693 1193</p>
        </div>
        <div className="justify-start items-center gap-4 flex-row flex">
          <Image src={location} alt="Our office" />
          <p className="font-bold underline">
            ICO-210, Raja 4c, Tallinn, Harjumaa
          </p>
        </div>
      </div>
      <div className="justify-between items-center md:items-end gap-8 flex-col flex">
        <div className="justify-between items-center gap-6 flex-row flex">
          <FacebookLink />
          <div className="w-[2px] h-[24px] bg-light" />
          <InstagramLink />
          <div className="w-[2px] h-[24px] bg-light" />
          <GitHubLink />
        </div>
        <div className="justify-between items-center gap-6 flex-row flex">
          <Link href="https://hub.ituk.ee/">
            <Image src={hub} alt="Hub" />
          </Link>
          <Link href="/stiil">
            <p className="font-bold underline">Stiiliraamat</p>
          </Link>
        </div>
        <p className="font-bold">© ITÜK 2016-2024</p>
      </div>
    </footer>
  );
}

// ituk/src/components/Footer.vue
<script setup lang="ts">
import { useI18n } from 'vue-i18n';  // Import useI18n to access the i18n instance
import Facebook from './buttons/social/Facebook.vue';
import GitHub from './buttons/social/GitHub.vue';
import Instagram from './buttons/social/Instagram.vue';
import PageButton from './buttons/TertiaryButton.vue';
import router from '@/router';

const { t, locale } = useI18n(); // Destructure `t` for translation and `locale` to set language

// Check if the route is active
const isActive = (path: string) => {
    return router.currentRoute.value.path == path;
};

// Change the language when clicking a link
const changeLanguage = (lang: string) => {
    locale.value = lang; // Change the current language locale
};
</script>

<template>
    <div
        class="w-screen min-h-72 h-full px-32 py-16 bg-dark shadow-filled flex-col justify-between items-center gap-16 flex">
        <div class="justify-start items-center gap-8 flex">
            <Facebook link="https://www.facebook.com/ituk.taltech/" />
            <img src="@/assets/icons/separator.svg" alt="/">
            <Instagram link="https://www.instagram.com/ituk.taltech" />
            <img src="@/assets/icons/separator.svg" alt="/">
            <GitHub link="https://github.com/ituk-ttu/" />
        </div>
        <div class="flex-col sm:flex-row justify-center items-center gap-12 flex">
            <p>
                <a class="underline cursor-pointer" to="#" @click.prevent="changeLanguage('en')">{{ $t('english')
                    }}</a>&nbsp;/&nbsp;<a class="underline cursor-pointer" to="#"
                    @click.prevent="changeLanguage('et')">{{
                        $t('estonian') }}</a>
            </p>
            <p class="button-text">©&nbsp;ITÜK&nbsp;2016-2024</p>
            <PageButton to='/style' :active="isActive('/style')" :text="$t('style')" />
        </div>
    </div>
</template>
