// synnipaev/src/components/buttons/button.tsx
"use client";

import React from "react";
import { useRouter, usePathname } from "next/navigation"; // Use Next.js App Router

interface ButtonProps {
  children?: React.ReactNode;
  text?: string;
  type?: "button" | "submit" | "reset"; // Specify valid button types
  variant: "primary" | "secondary" | "tertiary";
  big?: boolean;
  active?: boolean;
  to?: string; // Internal navigation path
  href?: string; // External link
  ariaLabel?: string;
  className?: string; // Allow custom class names to be passed
  onClick?: (event: React.MouseEvent<HTMLButtonElement>) => void; // MouseEvent type
}

const Button: React.FC<ButtonProps> = ({
  children,
  text,
  type = "button", // Default to "button"
  variant,
  big = false,
  active,
  to,
  href,
  ariaLabel,
  className = "",
  onClick,
}) => {
  const router = useRouter();
  const pathname = usePathname();

  const isActive = to && pathname === to; // Check if the current path matches the `to` prop

  const handleClick = (event: React.MouseEvent<HTMLButtonElement>) => {
    onClick?.(event); // Pass the event to the `onClick` prop
    event.preventDefault();
    if (href) {
      window.location.href = href; // Redirect to external link
    } else if (to) {
      router.push(to); // Internal navigation using Next.js's router
    }
  };

  const baseClasses = `flex justify-center items-center transition-colors duration-150 ${className}`;

  const variantClasses = {
    primary: `bg-primary shadow-filled rounded text-light hover:bg-secondary focus:bg-light focus:text-primary ${big ? "min-w-32 min-h-16 px-8 big-button-text" : "min-w-32 min-h-12 px-8"
      }`,
    secondary: `bg-transparent shadow-filled rounded box-border border-primary border-4 text-light hover:border-light focus:bg-light focus:border-light focus:text-primary ${big ? "min-w-32 min-h-16 px-8 big-button-text" : "min-w-32 min-h-12 px-8"
      }`,
    tertiary: `bg-transparent border-b-4 h-12 px-2 ${isActive || active
      ? "border-primary text-light"
      : "border-transparent text-light hover:border-light focus:border-primary focus:text-light"
      }`,
  };

  return (
    <button
      className={`${baseClasses} ${variantClasses[variant]}`}
      aria-label={ariaLabel || text}
      onClick={handleClick}
      type={type} // Pass the `type` here to the button attribute
    >
      {children || text} {/* Render `children` or `text` */}
    </button>
  );
};

export default Button;

// src/lib/components/Button.svelte
<script lang="ts">
    interface Props {
        text?: string;
        variant?: "primary" | "secondary" | "tertiary";
        size?: "sm" | "md" | "lg";
        disabled?: boolean;
        to?: string;
        href?: string;
        ariaLabel?: string;
        class?: string;
        type?: "button" | "submit" | "reset";
        onclick?: (event: MouseEvent) => void;
    }

    let {
        text,
        variant = "primary",
        size = "md",
        disabled = false,
        to,
        href,
        ariaLabel,
        class: className = "",
        type = "button",
        onclick,
        children,
    }: Props & { children?: import("svelte").Snippet } = $props();

    const sizeClasses: Record<string, string> = {
        sm: "min-w-24 px-3 py-1.5 btn-sm",
        md: "min-w-24 px-4 py-2 btn-md",
        lg: "min-w-24 px-6 py-3 btn-lg",
    };

    const variantClasses: Record<string, string> = {
        primary:
            "bg-primary text-white hover:brightness-[1.2] active:brightness-[0.7]",
        secondary:
            "bg-transparent border-4 border-primary text-white hover:bg-primary/20 active:bg-primary/30",
        tertiary:
            "bg-transparent text-white hover:bg-primary/20 active:bg-primary/30",
    };

    const baseClasses = $derived(`
		flex box-border justify-center items-center
		button-text uppercase
		rounded overflow-hidden
		transition-all duration-150 ease-in-out
		${sizeClasses[size]}
		${disabled ? "opacity-30 cursor-not-allowed" : "cursor-pointer"}
		${className}
	`);

    const combinedClasses = $derived(
        `${baseClasses} ${disabled ? "opacity-30" : variantClasses[variant]}`,
    );

    const isExternal = $derived(
        to?.startsWith("http://") || to?.startsWith("https://"),
    );
</script>

{#if to}
    {#if isExternal}
        <a
            class={combinedClasses}
            aria-label={ariaLabel || text}
            href={to}
            target="_blank"
            rel="noopener noreferrer"
            onclick={disabled ? (e) => e.preventDefault() : onclick}
        >
            {#if children}{@render children()}{:else}{text}{/if}
        </a>
    {:else}
        <a
            class={combinedClasses}
            aria-label={ariaLabel || text}
            href={to}
            onclick={disabled ? (e) => e.preventDefault() : onclick}
        >
            {#if children}{@render children()}{:else}{text}{/if}
        </a>
    {/if}
{:else if href}
    <a
        class={combinedClasses}
        aria-label={ariaLabel || text}
        {href}
        download
        onclick={disabled ? (e) => e.preventDefault() : onclick}
    >
        {#if children}{@render children()}{:else}{text}{/if}
    </a>
{:else}
    <button
        class={combinedClasses}
        aria-label={ariaLabel || text}
        {onclick}
        {type}
        {disabled}
    >
        {#if children}{@render children()}{:else}{text}{/if}
    </button>
{/if}
